name: JUnit-Frontends

on:
  pull_request:
    paths:
      - 'frontends/**'
      - '.github/workflows/jvm-unit-test.yml'
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: JUnit-Frontends
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v3.1.0
    - name: Set up OpenJDK 11
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Test Maven Build
      run: cd frontends/java && mvn --batch-mode -DskipTests clean package
    - name: Unit Test
      run: cd frontends/java && mvn --batch-mode test
